# Generated by Django 4.1.5 on 2023-01-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlist',
            name='type',
        ),
        migrations.AddField(
            model_name='eventlist',
            name='event_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='short_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
