# Generated by Django 4.1.5 on 2023-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0002_remove_eventlist_type_eventlist_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='local_dtg',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
