# Generated by Django 4.1.5 on 2023-02-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0003_eventlist_local_dtg'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
