# Generated by Django 4.1.5 on 2023-02-08 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_list', '0004_eventlist_lat_eventlist_lon_alter_eventlist_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlist',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='eventlist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='recent_searches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='saved_searches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
