# Generated by Django 4.1.5 on 2023-02-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0005_alter_eventlist_options_eventlist_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventlist',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='recent_searches',
        ),
        migrations.RemoveField(
            model_name='eventlist',
            name='saved_searches',
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eventlist',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
