# Generated by Django 4.1.5 on 2023-02-14 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_list', '0006_alter_eventlist_options_remove_eventlist_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
